version: "3.3"

services:
  database:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard:0.1.2
    ports:
      - "9842:3000"
    environment:
      - MYSQL_HOST=database
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - TZ=${TZ}

    volumes:
      - ${FILE_VOLUME_PATH}:/usr/app/files
      - ${FILE_VOLUME_PATH}/waivers:/usr/app/files/waivers
      - ${FILE_VOLUME_PATH}/images:/usr/app/files/images

    depends_on:
      - database

    pull_policy: build
    restart: always
