import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-tedx-white`}>
        <Providers>
          <main className="flex">
            <Sidebar />
            <section className="ml-16 w-full">{children}</section>
            {/* Yes that margin is scuffed */}
          </main>
        </Providers>
      </body>
    </html>
  );
}
